//GET persons
export const FETCH_PEOPLE_PENDING = "FETCH_PEOPLE_PENDING";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const FETCH_PEOPLE_FAIL = "FETCH_PEOPLE_FAIL";

//POST persons
export const POST_PEOPLE_PENDING = "POST_PEOPLE_PENDING";
export const POST_PEOPLE_SUCCESS = "POST_PEOPLE_SUCCESS";
export const POST_PEOPLE_FAIL = "POST_PEOPLE_FAIL";
